// examples/vue/src/App.vue
<script setup lang="ts">
import { computed } from "vue";
import { useWcBindable } from "@wc-bindable/vue";
import type { Auth, AuthSession, AuthValues } from "@csbc-dev/auth0";

interface SessionValues {
  ready: boolean;
  connecting: boolean;
  error: Error | null;
}

interface FacadeValues {
  count: number;
  connectedUser: string;
}
interface FacadeElement extends HTMLElement, FacadeValues {
  increment?: (...args: unknown[]) => Promise<unknown>;
  decrement?: (...args: unknown[]) => Promise<unknown>;
  reset?: (...args: unknown[]) => Promise<unknown>;
}

const env = import.meta.env;
const redirectUri = window.location.origin;

function errorText(err: unknown): string {
  if (!err) return "";
  if (err instanceof Error) return err.message;
  if (typeof err === "object" && err !== null && "error" in err) {
    return String((err as { error: string }).error);
  }
  return String(err);
}

const authBinding    = useWcBindable<Auth, AuthValues>();
const sessionBinding = useWcBindable<AuthSession, SessionValues>();
// Bind directly on the payload child — the session mirrors property
// updates onto it, so `useWcBindable` against the facade observes the
// live Core surface with no manual proxy bridging.
const facadeBinding  = useWcBindable<FacadeElement, FacadeValues>();

const auth    = authBinding.values;
const session = sessionBinding.values;
const facade  = facadeBinding.values;

const status = computed(() => {
  if (auth.loading)              return "Loading Auth0…";
  if (!auth.authenticated)       return "Signed out.";
  if (session.ready)             return "Session ready.";
  if (session.connecting)        return "Opening session…";
  return "Authenticated, waiting for session…";
});

function login() { authBinding.ref.value?.login(); }
function logout() {
  authBinding.ref.value?.logout({ logoutParams: { returnTo: redirectUri } });
}
// Command forwarders return a Promise that rejects if the proxy can't
// reach the server — e.g. a click that races a disconnect, in the window
// before the `ready` guard removes the buttons. Swallow-and-log so it
// doesn't bubble up as an unhandledrejection.
function reportCmdError(err: unknown) { console.warn("command failed:", err); }
function increment() { facadeBinding.ref.value?.increment?.()?.catch(reportCmdError); }
function decrement() { facadeBinding.ref.value?.decrement?.()?.catch(reportCmdError); }
function reset()     { facadeBinding.ref.value?.reset?.()?.catch(reportCmdError); }
</script>

<template>
  <main>
    <h1>Vue — remote mode</h1>

    <auth0-gate
      :ref="authBinding.ref"
      id="auth"
      :domain="env.VITE_AUTH0_DOMAIN"
      :client-id="env.VITE_AUTH0_CLIENT_ID"
      :audience="env.VITE_AUTH0_AUDIENCE"
      :remote-url="env.VITE_REMOTE_URL || 'ws://localhost:3000'"
      :redirect-uri="redirectUri"
    />
    <auth0-session :ref="sessionBinding.ref" target="auth">
      <app-core-facade :ref="facadeBinding.ref" />
    </auth0-session>

    <section>
      <p class="muted">{{ status }}</p>
      <p v-if="auth.error" class="err">Auth error: {{ errorText(auth.error) }}</p>
      <p v-if="session.error" class="err">Session error: {{ errorText(session.error) }}</p>

      <button v-if="!auth.loading && !auth.authenticated" @click="login">Sign in</button>
      <button v-if="auth.authenticated" @click="logout">Sign out</button>
    </section>

    <section v-if="session.ready">
      <p>Count: <strong>{{ facade.count ?? 0 }}</strong></p>
      <p class="muted">Connected as: {{ facade.connectedUser ?? "" }}</p>
      <div class="row">
        <button @click="increment">+1</button>
        <button @click="decrement">−1</button>
        <button @click="reset">Reset</button>
      </div>
    </section>
  </main>
</template>

<style>
main { font: 14px/1.5 system-ui, sans-serif; max-width: 480px; margin: 2rem auto; padding: 0 1rem; }
section { margin: 1rem 0; padding: 1rem; border: 1px solid #ddd; border-radius: 6px; }
button { font: inherit; padding: 0.4rem 0.8rem; }
.row > * + * { margin-left: 0.5rem; }
.muted { color: #666; }
.err { color: #b00; }
</style>

// examples/react/src/App.tsx
import type { ReactNode } from "react";
import { useWcBindable } from "@wc-bindable/react";
import type { Auth, AuthSession, AuthValues } from "@csbc-dev/auth0";

interface SessionValues {
  ready: boolean;
  connecting: boolean;
  error: Error | null;
}

// Properties + commands declared on AppCoreFacade (server-mirrored).
interface FacadeValues {
  count: number;
  connectedUser: string;
}
interface FacadeElement extends HTMLElement, FacadeValues {
  // Command forwarders installed by <auth0-session> at connect time.
  // Marked optional because they do NOT exist on the element before the
  // session connects: <auth0-session> writes them as own-property
  // forwarders on the payload child once the proxy is built. Once
  // `sessionValues.ready === true` they are guaranteed to be present —
  // <auth0-session> installs the forwarders synchronously BEFORE
  // registering `bind()`, and `ready` only flips after `bind()` has
  // dispatched its first batch. The `ready && ...` render guard below is
  // therefore the contract that makes the `.increment?.()` call safe.
  increment?: (...args: unknown[]) => Promise<unknown>;
  decrement?: (...args: unknown[]) => Promise<unknown>;
  reset?: (...args: unknown[]) => Promise<unknown>;
}

// Command forwarders return a Promise that rejects if the proxy can't
// reach the server — e.g. a click that races a disconnect, in the window
// before the `ready` render guard removes the buttons. Swallow-and-log so
// it doesn't bubble up as an unhandledrejection.
function reportCmdError(err: unknown) {
  console.warn("command failed:", err);
}

function errorText(err: unknown): string {
  if (!err) return "";
  if (err instanceof Error) return err.message;
  if (typeof err === "object" && err !== null && "error" in err) {
    return String((err as { error: string }).error);
  }
  return String(err);
}

const env = import.meta.env;

export default function App() {
  const [authRef, authValues] = useWcBindable<Auth, AuthValues>();
  const [sessionRef, sessionValues] = useWcBindable<AuthSession, SessionValues>();
  // Bind directly on the payload child — the session mirrors property
  // updates onto it as own data properties + the user-declared events,
  // so `useWcBindable` against the facade sees the live Core surface
  // with no manual proxy bridging. The same ref is what we call command
  // forwarders through in the click handlers below; no second ref needed.
  const [facadeRef, facadeValues] = useWcBindable<FacadeElement, FacadeValues>();

  const status =
    authValues.loading           ? "Loading Auth0…" :
    !authValues.authenticated    ? "Signed out." :
    sessionValues.ready          ? "Session ready." :
    sessionValues.connecting     ? "Opening session…" :
                                   "Authenticated, waiting for session…";

  return (
    <main style={{ font: "14px/1.5 system-ui, sans-serif", maxWidth: 480, margin: "2rem auto", padding: "0 1rem" }}>
      <h1>React — remote mode</h1>

      <auth0-gate
        ref={authRef}
        id="auth"
        domain={env.VITE_AUTH0_DOMAIN}
        client-id={env.VITE_AUTH0_CLIENT_ID}
        audience={env.VITE_AUTH0_AUDIENCE}
        remote-url={env.VITE_REMOTE_URL || "ws://localhost:3000"}
        redirect-uri={window.location.origin}
      />
      <auth0-session ref={sessionRef} target="auth">
        <app-core-facade ref={facadeRef} />
      </auth0-session>

      <Section>
        <p style={{ color: "#666" }}>{status}</p>
        {authValues.error && <p style={{ color: "#b00" }}>Auth error: {errorText(authValues.error)}</p>}
        {sessionValues.error && <p style={{ color: "#b00" }}>Session error: {errorText(sessionValues.error)}</p>}

        {!authValues.loading && !authValues.authenticated && (
          <button onClick={() => authRef.current?.login()}>Sign in</button>
        )}
        {authValues.authenticated && (
          <button onClick={() => authRef.current?.logout({ logoutParams: { returnTo: window.location.origin } })}>
            Sign out
          </button>
        )}
      </Section>

      {sessionValues.ready && (
        <Section>
          <p>Count: <strong>{facadeValues.count ?? 0}</strong></p>
          <p style={{ color: "#666" }}>Connected as: {facadeValues.connectedUser ?? ""}</p>
          <Row>
            <button onClick={() => facadeRef.current?.increment?.()?.catch(reportCmdError)}>+1</button>
            <button onClick={() => facadeRef.current?.decrement?.()?.catch(reportCmdError)}>−1</button>
            <button onClick={() => facadeRef.current?.reset?.()?.catch(reportCmdError)}>Reset</button>
          </Row>
        </Section>
      )}
    </main>
  );
}

function Section({ children }: { children: ReactNode }) {
  return <section style={{ margin: "1rem 0", padding: "1rem", border: "1px solid #ddd", borderRadius: 6 }}>{children}</section>;
}
function Row({ children }: { children: ReactNode }) {
  return <div style={{ display: "flex", gap: "0.5rem" }}>{children}</div>;
}
